publish to wire-builds (#4445)
* refactor: branch vs pr pipelines

* reinstate lint

* always push docker image

* target branch

* Add helm chart

* publish helm chart

* Add publish to wire-builds step

* fix debug

* fix: upgrade account-pages

* fix: image_tag not defined as output

* Remove test triggers

* test: update to remove warnings

* chore: update prettier plugin

* chore: trying to fix deps

* chore: fix

---------

Co-authored-by: Timothy LeBon <tlebon@gmail.com>

diff --git a/.github/workflows/test_build_deploy.yml b/.github/workflows/test_build_deploy.yml
--- a/.github/workflows/test_build_deploy.yml
+++ b/.github/workflows/test_build_deploy.yml
@@ -5,8 +5,6 @@ on:
     branches: [staging, main]
     tags:
       - v*
-  pull_request:
-    branches: [staging, main]
 
 jobs:
   test_build_deploy:
@@ -17,11 +15,14 @@ jobs:
         DISTRIBUTION: ['DISTRIBUTION_0']
 
     env:
-      TEST_COVERAGE_FAIL_THRESHOLD: 10
-      TEST_COVERAGE_WARNING_THRESHOLD: 50
       DEPLOYMENT_RECOVERY_TIMEOUT_SECONDS: 150
       AWS_APPLICATION_NAME: Account
       AWS_BUILD_ZIP_PATH: 'wire-account.zip'
+
+    outputs:
+      wire_builds_target_branches: ${{ steps.output_target_branches.outputs.wire_builds_target_branches }}
+      chart_version: ${{ steps.publish_helm_chart.outputs.chart_version }}
+      image_tag: ${{ steps.push_docker_image.outputs.image_tag }}
 
     steps:
       - name: Checkout
@@ -56,6 +57,26 @@ jobs:
         if: contains(env.TITLE || env.COMMIT_MESSAGE, '[skip ci]') || contains(env.TITLE || env.COMMIT_MESSAGE, '[ci skip]')
         uses: andymckay/cancel-action@0.3
 
+      - name: Define target branches in wireapp/wire-builds to bump
+        id: output_target_branches
+        shell: bash
+        run: |
+          # NOTE: make sure that wire_builds_target_branches is valid JSON
+          wire_builds_target_branches='[]'
+
+          version_tag="${TAG:-$BRANCH_NAME}"
+
+          if [[ "$version_tag" == *"production"* ]]; then
+            echo "FUTUREWORK: bump some production branch on wire-builds once it exists"
+          fi
+
+          if [ "$version_tag" == "staging" ]; then
+            wire_builds_target_branches='["dev"]'
+          fi
+
+          echo "wire_builds_target_branches: $wire_builds_target_branches"
+          echo "wire_builds_target_branches=$wire_builds_target_branches" >> $GITHUB_OUTPUT
+
       - name: Cancel Previous Runs
         uses: styfle/cancel-workflow-action@0.12.0
         with:
@@ -75,15 +96,6 @@ jobs:
       - name: Test
         run: yarn test
 
-      - name: Monitor coverage
-        if: github.event_name == 'pull_request' && ! contains(github.event.pull_request.user.login, 'dependabot[bot]')
-        uses: slavcodev/coverage-monitor-action@1.8.0
-        with:
-          github_token: ${{github.token}}
-          coverage_path: 'coverage/clover.xml'
-          threshold_alert: ${{env.TEST_COVERAGE_FAIL_THRESHOLD}}
-          threshold_warning: ${{env.TEST_COVERAGE_WARNING_THRESHOLD}}
-
       - name: Create commit file
         run: |
           mkdir -p ./dist
@@ -96,27 +108,6 @@ jobs:
       - name: Build production
         if: env.TAG != ''
         run: yarn bundle:prod
-
-      - name: Assembling release information
-        if: env.TAG != '' && matrix.DISTRIBUTION == 'DISTRIBUTION_0'
-        # NOTE: always using 'main' config, since release version is only consumed at
-        #       'production' stage for now
-        # NOTE: 'containerImageTag' value must follow bin/push_docker.js:L49
-        shell: bash
-        env:
-          RELEASE_NAME: ${{env.TAG}}
-        run: |
-          configVersion=$(cat ./app-config/package.json | jq -r '.dependencies["wire-web-config-default-main"]' | awk -F '#' '{ print $2 }')
-          packageVersion=$(cat ./package.json | jq -r '.version')
-          containerImageTag="${packageVersion}-${configVersion}-${GITHUB_SHA::7}"
-          echo "{\"imageTag\": \"${containerImageTag}\", \"releaseName\": \"${RELEASE_NAME}\"}" > ./release-info.json
-
-      - name: Storing release information
-        if: env.TAG != '' && matrix.DISTRIBUTION == 'DISTRIBUTION_0'
-        uses: actions/upload-artifact@v4
-        with:
-          name: release-info.json
-          path: ./release-info.json
 
       - name: Deploy staging build to Elastic Beanstalk
         if: env.BRANCH_NAME == 'staging' && matrix.DISTRIBUTION == 'DISTRIBUTION_0'
@@ -148,29 +139,57 @@ jobs:
           version_label: ${{env.TAG}}-${{github.run_id}}
           version_description: ${{github.sha}}
 
-      - name: Push staging Docker image
-        if: env.BRANCH_NAME == 'staging'
+      - name: Push Docker image
+        id: push_docker_image
         env:
           DOCKER_PASSWORD: ${{secrets.WEBTEAM_QUAY_PASSWORD}}
           DOCKER_USERNAME: ${{secrets.WEBTEAM_QUAY_USERNAME}}
         run: |
+          dist=$DISTRIBUTION
           if [ "$DISTRIBUTION" == "wire" ]; then
-            yarn docker '' staging
-          else
-            yarn docker "$DISTRIBUTION" staging
+            dist=""
           fi
+          stage="$BRANCH_NAME"
+          if [ "$TAG" != "" ]; then
+            stage="production"
+          fi
+          yarn docker "$dist" "$stage" ${GITHUB_SHA} ./tag.txt
+          echo "image_tag=$(cat ./tag.txt)" >> $GITHUB_OUTPUT
+          echo "Pushed also unique docker tag $image_tag"
 
-      - name: Push production Docker image
-        if: env.TAG != ''
+      - uses: azure/setup-helm@v3
+        with:
+          version: '3.12.2'
+        id: install
+
+      - name: Publish Helm chart
+        shell: bash
+        id: publish_helm_chart
         env:
-          DOCKER_PASSWORD: ${{secrets.WEBTEAM_QUAY_PASSWORD}}
-          DOCKER_USERNAME: ${{secrets.WEBTEAM_QUAY_USERNAME}}
+          AWS_ACCESS_KEY_ID: ${{ secrets.CHARTS_WEBAPP_AUTOMATION_AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.CHARTS_WEBAPP_AUTOMATION_AWS_SECRET_ACCESS_KEY }}
         run: |
-          if [ "$DISTRIBUTION" == "wire" ]; then
-            yarn docker '' production
+          set -eo pipefail
+
+          image_tag="${{steps.push_docker_image.outputs.image_tag}}"
+
+          helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.15.1
+
+          helm repo add charts-webapp s3://public.wire.com/charts-webapp
+
+          if [ "$TAG" != "" ]; then
+            chart_version="$(./bin/chart-next-version.sh release)"
           else
-            yarn docker "$DISTRIBUTION" production
+            chart_version="$(./bin/chart-next-version.sh prerelease)"
           fi
+          echo "chart_version=$chart_version" >> $GITHUB_OUTPUT
+
+          chart_patched="$(yq -Mr ".version = \"$chart_version\" | .appVersion = \"$image_tag\"" ./charts/account-pages/Chart.yaml)"
+          echo "$chart_patched" > ./charts/account-pages/Chart.yaml
+
+          helm package ./charts/account-pages
+
+          helm s3 push account-pages-*.tgz charts-webapp
 
       - name: Create GitHub release
         id: create_release
@@ -185,71 +204,65 @@ jobs:
           draft: false
           prerelease: false
 
-  update_helm_chart:
-    name: Update Helm chart
+  publish_wire_builds:
+    name: Bump account-pages chart in wire-builds
     runs-on: ubuntu-latest
-
     needs: test_build_deploy
 
-    steps:
-      # INFO: https://github.com/wireapp/wire-webapp/blob/062ae4e1c23fa0b33dafae9cc0acf9a94fa8ad1a/.github/workflows/test_build_deploy.yml#L351-L356
-      - name: Obtaining release information artifact
-        id: release-info-artifact
-        uses: actions/download-artifact@v4
-        continue-on-error: true
-        with:
-          name: release-info.json
-      - name: Indicating whether release info exist
-        id: release-info-file
-        env:
-          ARTIFACT_LOCAL_PATH: '${{ steps.release-info-artifact.outputs.download-path }}/release-info.json'
-        shell: bash
-        run: |
-          test -s "${ARTIFACT_LOCAL_PATH}" && echo '::set-output name=exists::true'
-          echo "::set-output name=releaseInfo::$(cat ${ARTIFACT_LOCAL_PATH})"
+    strategy:
+      matrix:
+        target_branch: ${{fromJSON(needs.test_build_deploy.outputs.wire_builds_target_branches)}}
 
-      - name: Checking out 'wire-server'
+    steps:
+      - name: Check out wire-builds
         uses: actions/checkout@v4
-        if: ${{ steps.release-info-file.outputs.exists == 'true' }}
         with:
-          repository: 'wireapp/wire-server'
+          repository: wireapp/wire-builds
+          token: ${{secrets.WIRE_BUILDS_WRITE_ACCESS_GH_TOKEN}}
+          ref: ${{matrix.target_branch}}
           fetch-depth: 1
 
-      - name: Changing Helm value of the account-pages chart
-        id: change-helm-value
-        if: ${{ steps.release-info-file.outputs.exists == 'true' }}
+      - name: Create new build in wire-build
         shell: bash
         run: |
-          sed --in-place --expression="s/  tag: .*/  tag: \"${{ fromJSON(steps.release-info-file.outputs.releaseInfo).imageTag }}\"/" ./charts/account-pages/values.yaml
-          git add ./charts/account-pages/values.yaml
-          echo "Upgrade account-pages version to ${{ fromJSON(steps.release-info-file.outputs.releaseInfo).imageTag }}" > ./changelog.d/0-release-notes/account-pages-upgrade
-          git add ./changelog.d/0-release-notes/account-pages-upgrade
-          echo "::set-output name=releaseUrl::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/${{ fromJSON(steps.release-info-file.outputs.releaseInfo).releaseName }}"
+          set -eo pipefail
 
-      - name: Creating Pull Request
-        id: create-pr
-        if: ${{ steps.release-info-file.outputs.exists == 'true' }}
-        uses: peter-evans/create-pull-request@v5
-        with:
-          draft: false
-          token: ${{ secrets.ZEBOT_GH_TOKEN }}
-          author: 'Zebot <zebot@users.noreply.github.com>'
-          branch: charts-update-account-pages-image-tag-${{ github.run_number }}
-          commit-message: 'chore: [charts] Update account-pages version'
-          title: 'Update account-pages version in Helm chart [skip ci]'
-          body: |
-            Image tag: `${{ fromJSON(steps.release-info-file.outputs.releaseInfo).imageTag }}`
-            Release: [`${{ fromJSON(steps.release-info-file.outputs.releaseInfo).releaseName }}`](${{ steps.change-helm-value.outputs.releaseUrl }})
+          chart_version="${{needs.test_build_deploy.outputs.chart_version}}"
 
-      - name: Printing Pull Request URL
-        if: ${{ steps.release-info-file.outputs.exists == 'true' }}
-        shell: bash
-        run: |
-          echo "PR: ${{ steps.create-pr.outputs.pull-request-url }}"
+          git config --global user.email "zebot@users.noreply.github.com"
+          git config --global user.name "Zebot"
 
-      - name: Delete release artifact
-        uses: geekyeggo/delete-artifact@v4
-        with:
-          failOnError: false
-          name: |
-            release-info.json
+          image_tag="${{needs.test_build_deploy.outputs.image_tag}}"
+
+          for retry in $(seq 3); do
+            (
+            set -e
+
+            if (( retry > 1 )); then
+             echo "Retrying..."
+            fi
+
+            git fetch --depth 1 origin "${{ matrix.target_branch }}"
+            git checkout "${{ matrix.target_branch }}"
+            git reset --hard @{upstream}
+
+            build_json=$(cat ./build.json | \
+              ./bin/set-chart-fields account-pages \
+              "version=$chart_version" \
+              "repo=https://s3-eu-west-1.amazonaws.com/public.wire.com/charts-webapp" \
+              "meta.appVersion=$image_tag" \
+              "meta.commitURL=${{github.event.head_commit.url}}" \
+              "meta.commit=${{github.event.head_commit.id}}" \
+            | ./bin/bump-prerelease )
+            echo "$build_json" > ./build.json
+
+            git add build.json
+            git commit -m "Bump account-pages to $chart_version"
+            git push origin "${{ matrix.target_branch }}"
+
+            ) && break
+          done
+          if (( $? != 0 )); then
+              echo "Retrying didn't help. Failing the step."
+              exit 1
+          fi
